[package]
name = "haikulang_cli"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
haikulang_parser = { path = "../haikulang_parser" }
rustyline.workspace = true

[lints]
workspace = true
